server:
  port: 8001
  tomcat:
    #tomcat线程池大小设置
    max-threads: 1000
    #tomcat初始化线程数量
    min-spare-threads: 30
    #tomcat编码
    uri-encoding: UTF-8



spring:
  autoconfigure:
    exclude: com.alibaba.druid.spring.boot.autoconfigure.DruidDataSourceAutoConfigure
  application:
    name: shop-admin
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  jackson:
    date-format: yyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  banner:
    charset: UTF-8 #banner字符集
    location: classpath:banner.txt #
  datasource:
    dynamic:
      primary: master_1 #设置默认的数据源或者数据源组,默认值即为master
      strict: false #设置严格模式,默认false不启动. 启动后在未匹配到指定数据源时候会抛出异常,不启动则使用默认数据源.
      datasource:
        master_1:
          url: jdbc:mysql://127.0.0.1:3306/shop-admin?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        master_2:
          url: jdbc:mysql://127.0.0.1:3306/ssmp-wx-member?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        master_3:
          url: jdbc:mysql://127.0.0.1:3306/ssmp-wx-order?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
        master_4:
          url: jdbc:mysql://127.0.0.1:3306/ssmp-wx-product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
          username: root
          password: root
          driver-class-name: com.mysql.cj.jdbc.Driver
    #fiters一定要放在datasource下，如果放到druid下，SQL监控不生效
    filters: stat, wall, log4j2
    druid:
      # 初始化大小，最小，最大
      initialSize: 5
      minIdle: 5
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 合并多个DruidDataSource的监控数据
      useGlobalDataSourceStat: true
      aop-patterns: com.complain.*.service.*, com.complain.*.dao.*
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 10
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        #login-username: admin
        #login-password: admin
  servlet:
    multipart:
      enabled: true
      max-file-size: 20MB
      max-request-size: 200MB

redis:
  host: 127.0.0.1
  database: 0
  password:
  port: 6379
  timeout: 30000


cos:
  accessKeyId: AKIDNVDg04Z0atv0rQh16uQm24oHYcPupLHw
  accessKeySecret: ZS7VdqlSuGNEo84mDNbcNr5OTIqKbcMq
  bucketName: shop-admin-1300029934


mybatis-plus:
  global-config:
    banner: false
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #开启sql日志