server:
  port: 8021


spring:
  cloud:
    nacos:
      server-addr: 127.0.0.1:8848
      discovery:
        username: nacos
        password: nacos
        namespace: public
  application:
    name: stock-server # 应用的名称（nacos会将该名称当做服务名称）
